name: Accurro AS
favicon: null
layout_spectrum: 0.01243
typography_spectrum: 0.23798073595389724
title: Accurro
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040001'
    - '#ffffff'
    - '#a6c543'
    - '#676767'
    - '#670f11'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0.8765499736182392
purpose: []
